version: "3"
services:
  firefox:
    image: seleniarm/standalone-firefox
    ports:
      - "5900:5900"
      - "4444:4444"

  maven:
    image: maven
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: $PWD
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.m2:/root/.m2
    command: bash -c "mvn clean install &&
            mvn verify -pl functionaltest
            -Dbrowser.remote_uri='http://127.0.0.1:4444/wd/hub'
            -Dtest.url='https://www.mailtravel.co.uk/'
            -Dskip.tests='false'
            -Dbrowser.type='firefox'"



